# Travis CI Config - https://docs.travis-ci.com/user/languages/java/
language: java

# Improve Build Speed - https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

# Customizing The Build - https://docs.travis-ci.com/user/customizing-the-build/
install:
- if [ "$DESC" = "H2 test with oraclejdk10" ] || [ "$DESC" = "H2 test with openjdk10" ];
  then mvn install -P h2-database -D skipTests=true -D maven.javadoc.skip=true -B -V;
  fi

script:
- if [ "$DESC" = "H2 test with oraclejdk10" ] || [ "$DESC" = "H2 test with openjdk10" ];
  then mvn test -P h2-database -B;
  fi

# Matrix Expansion - https://docs.travis-ci.com/user/build-stages/matrix-expansion/
matrix:
  fast_finish: true
  include:
  - jdk: oraclejdk10
    env: DESC="H2 test with oraclejdk10"
  - jdk: openjdk10
    env: DESC="H2 test with openjdk10"

# Codecov - https://github.com/codecov/example-java
after_success:
- bash <(curl -s https://codecov.io/bash)

# Notifications - https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
    - qThegamEp@gmail.com
    on_success: always
    on_failure: always
